from __future__ import annotations

from .shared import MODULES_ROOT, package_dirs

CORE_ROOT = MODULES_ROOT / 'core'

CORE_PUBLIC_ROOT = CORE_ROOT / 'public'
CORE_PUBLIC_HTTP_ROOT = CORE_PUBLIC_ROOT / 'http'
CORE_PUBLIC_HTTP_PACKAGE_DIRS = package_dirs(CORE_PUBLIC_HTTP_ROOT, ('app',))
CORE_PUBLIC_SERVICES_ROOT = CORE_PUBLIC_ROOT / 'services'
CORE_PUBLIC_SERVICE_PACKAGE_DIRS = package_dirs(CORE_PUBLIC_SERVICES_ROOT, ('runtime',))
CORE_PUBLIC_TOOLING_ROOT = CORE_PUBLIC_ROOT / 'tooling'
CORE_PUBLIC_TOOLING_PACKAGE_DIRS = package_dirs(CORE_PUBLIC_TOOLING_ROOT, ('compat', 'smoke'))
CORE_PUBLIC_PACKAGE_DIRS = [
    CORE_PUBLIC_ROOT,
    *CORE_PUBLIC_HTTP_PACKAGE_DIRS,
    *CORE_PUBLIC_SERVICE_PACKAGE_DIRS,
    *CORE_PUBLIC_TOOLING_PACKAGE_DIRS,
]

CORE_PARSING_ROOT = CORE_ROOT / 'parsing'
CORE_PARSING_EXPRESSION_ROOT = CORE_PARSING_ROOT / 'expressions'
CORE_PARSING_EXPRESSION_PACKAGE_DIRS = package_dirs(
    CORE_PARSING_EXPRESSION_ROOT,
    ('parser', 'rendering'),
)
CORE_PARSING_PACKAGE_DIRS = [
    CORE_PARSING_ROOT,
    *CORE_PARSING_EXPRESSION_PACKAGE_DIRS,
    CORE_PARSING_ROOT / 'input',
    CORE_PARSING_ROOT / 'quantities',
    CORE_PARSING_ROOT / 'text',
]

CORE_ENGINES_ROOT = CORE_ROOT / 'engines'
CORE_ENGINE_EXPRESSIONS_ROOT = CORE_ENGINES_ROOT / 'expressions'
CORE_ENGINE_EXPRESSION_PACKAGE_DIRS = package_dirs(
    CORE_ENGINE_EXPRESSIONS_ROOT,
    ('base', 'math', 'mixed', 'simple'),
)
CORE_ENGINE_PACKAGE_DIRS = [
    CORE_ENGINES_ROOT,
    CORE_ENGINES_ROOT / 'columns',
    CORE_ENGINE_EXPRESSIONS_ROOT,
    *[path for path in CORE_ENGINE_EXPRESSION_PACKAGE_DIRS if path != CORE_ENGINE_EXPRESSIONS_ROOT],
]

CORE_EXPLANATIONS_ROOT = CORE_ROOT / 'explanations'
CORE_EXPLANATION_PACKAGE_DIRS = package_dirs(
    CORE_EXPLANATIONS_ROOT,
    ('advice_layer', 'dispatch', 'support', 'math'),
)

CORE_SUPPORT_ROOT = CORE_ROOT / 'support'
CORE_SUPPORT_PACKAGE_DIRS = package_dirs(
    CORE_SUPPORT_ROOT,
    ('safety', 'math', 'patching', 'postprocess'),
)

CORE_PACKAGE_DIRS = [
    CORE_ROOT,
    *CORE_PUBLIC_PACKAGE_DIRS,
    *CORE_PARSING_PACKAGE_DIRS,
    *CORE_ENGINE_PACKAGE_DIRS,
    *CORE_EXPLANATION_PACKAGE_DIRS,
    *CORE_SUPPORT_PACKAGE_DIRS,
]

__all__ = [
    'CORE_ENGINE_EXPRESSION_PACKAGE_DIRS',
    'CORE_ENGINE_EXPRESSIONS_ROOT',
    'CORE_ENGINE_PACKAGE_DIRS',
    'CORE_ENGINES_ROOT',
    'CORE_EXPLANATION_PACKAGE_DIRS',
    'CORE_EXPLANATIONS_ROOT',
    'CORE_PACKAGE_DIRS',
    'CORE_PARSING_EXPRESSION_PACKAGE_DIRS',
    'CORE_PARSING_EXPRESSION_ROOT',
    'CORE_PARSING_PACKAGE_DIRS',
    'CORE_PARSING_ROOT',
    'CORE_PUBLIC_HTTP_PACKAGE_DIRS',
    'CORE_PUBLIC_HTTP_ROOT',
    'CORE_PUBLIC_PACKAGE_DIRS',
    'CORE_PUBLIC_ROOT',
    'CORE_PUBLIC_SERVICE_PACKAGE_DIRS',
    'CORE_PUBLIC_SERVICES_ROOT',
    'CORE_PUBLIC_TOOLING_PACKAGE_DIRS',
    'CORE_PUBLIC_TOOLING_ROOT',
    'CORE_ROOT',
    'CORE_SUPPORT_PACKAGE_DIRS',
    'CORE_SUPPORT_ROOT',
]
