from __future__ import annotations

from .shared import MODULES_ROOT, package_dirs

HEALTH_ROOT = MODULES_ROOT / 'health'

HEALTH_AUDITS_ROOT = HEALTH_ROOT / 'audits'
HEALTH_AUDIT_ROUTING_ROOT = HEALTH_AUDITS_ROOT / 'routing'
HEALTH_AUDIT_ROUTING_PACKAGE_DIRS = package_dirs(HEALTH_AUDIT_ROUTING_ROOT, ('matrix', 'policy'))
HEALTH_AUDIT_QUALITY_ROOT = HEALTH_AUDITS_ROOT / 'quality'
HEALTH_AUDIT_QUALITY_PACKAGE_DIRS = package_dirs(HEALTH_AUDIT_QUALITY_ROOT, ('output',))
HEALTH_AUDIT_CONSISTENCY_ROOT = HEALTH_AUDITS_ROOT / 'consistency'
HEALTH_AUDIT_CONSISTENCY_PACKAGE_DIRS = package_dirs(HEALTH_AUDIT_CONSISTENCY_ROOT, ('cache',))
HEALTH_AUDIT_PACKAGE_DIRS = [
    HEALTH_AUDITS_ROOT,
    *HEALTH_AUDIT_ROUTING_PACKAGE_DIRS,
    *HEALTH_AUDIT_QUALITY_PACKAGE_DIRS,
    *HEALTH_AUDIT_CONSISTENCY_PACKAGE_DIRS,
]

HEALTH_CASES_ROOT = HEALTH_ROOT / 'cases'
HEALTH_BASELINES_ROOT = HEALTH_CASES_ROOT / 'baselines'
HEALTH_BASELINE_PACKAGE_DIRS = package_dirs(HEALTH_BASELINES_ROOT, ('regression', 'golden', 'snapshot'))
HEALTH_CASE_PACKAGE_DIRS = [
    HEALTH_CASES_ROOT,
    HEALTH_BASELINES_ROOT,
    *[path for path in HEALTH_BASELINE_PACKAGE_DIRS if path != HEALTH_BASELINES_ROOT],
    HEALTH_CASES_ROOT / 'matrix',
]

HEALTH_SUITES_ROOT = HEALTH_ROOT / 'suites'
HEALTH_CORE_CHECKS_ROOT = HEALTH_SUITES_ROOT / 'core_checks'
HEALTH_CORE_CHECK_BASELINES_ROOT = HEALTH_CORE_CHECKS_ROOT / 'baselines'
HEALTH_CORE_CHECK_BASELINE_PACKAGE_DIRS = package_dirs(
    HEALTH_CORE_CHECK_BASELINES_ROOT,
    ('regression', 'golden', 'snapshot'),
)
HEALTH_CORE_CHECK_HEALTHCHECK_ROOT = HEALTH_CORE_CHECKS_ROOT / 'healthcheck'
HEALTH_CORE_CHECK_HEALTHCHECK_BUILDERS_ROOT = HEALTH_CORE_CHECK_HEALTHCHECK_ROOT / 'builders'
HEALTH_CORE_CHECK_HEALTHCHECK_PACKAGE_DIRS = package_dirs(
    HEALTH_CORE_CHECK_HEALTHCHECK_ROOT,
    ('builders',),
)
HEALTH_CORE_CHECK_PACKAGE_DIRS = [
    HEALTH_CORE_CHECKS_ROOT,
    *HEALTH_CORE_CHECK_BASELINE_PACKAGE_DIRS,
    *HEALTH_CORE_CHECK_HEALTHCHECK_PACKAGE_DIRS,
]
HEALTH_STABILITY_ROOT = HEALTH_SUITES_ROOT / 'stability'
HEALTH_STABILITY_PERFORMANCE_ROOT = HEALTH_STABILITY_ROOT / 'performance'
HEALTH_STABILITY_PERFORMANCE_PACKAGE_DIRS = package_dirs(
    HEALTH_STABILITY_PERFORMANCE_ROOT,
    ('benchmarks',),
)
HEALTH_STABILITY_CONSISTENCY_ROOT = HEALTH_STABILITY_ROOT / 'consistency'
HEALTH_STABILITY_CONSISTENCY_PACKAGE_DIRS = package_dirs(
    HEALTH_STABILITY_CONSISTENCY_ROOT,
    ('determinism',),
)
HEALTH_STABILITY_PACKAGE_DIRS = [
    HEALTH_STABILITY_ROOT,
    *HEALTH_STABILITY_PERFORMANCE_PACKAGE_DIRS,
    *HEALTH_STABILITY_CONSISTENCY_PACKAGE_DIRS,
]
HEALTH_SUITES_PACKAGE_DIRS = [
    HEALTH_SUITES_ROOT,
    *HEALTH_CORE_CHECK_PACKAGE_DIRS,
    *HEALTH_STABILITY_PACKAGE_DIRS,
]

HEALTH_REPORTING_ROOT = HEALTH_ROOT / 'reporting'
HEALTH_REPORTING_EXPORTS_ROOT = HEALTH_REPORTING_ROOT / 'exports'
HEALTH_REPORTING_EXPORT_PACKAGE_DIRS = package_dirs(HEALTH_REPORTING_EXPORTS_ROOT, ('bundles',))
HEALTH_PRESENTATION_ROOT = HEALTH_REPORTING_ROOT / 'presentation'
HEALTH_PRESENTATION_MARKDOWN_ROOT = HEALTH_PRESENTATION_ROOT / 'markdown'
HEALTH_PRESENTATION_MARKDOWN_PACKAGE_DIRS = package_dirs(
    HEALTH_PRESENTATION_MARKDOWN_ROOT,
    ('render',),
)
HEALTH_PRESENTATION_SUMMARY_ROOT = HEALTH_PRESENTATION_ROOT / 'summary'
HEALTH_PRESENTATION_SUMMARY_PACKAGE_DIRS = package_dirs(
    HEALTH_PRESENTATION_SUMMARY_ROOT,
    ('core',),
)
HEALTH_PRESENTATION_PACKAGE_DIRS = [
    HEALTH_PRESENTATION_ROOT,
    *HEALTH_PRESENTATION_MARKDOWN_PACKAGE_DIRS,
    *HEALTH_PRESENTATION_SUMMARY_PACKAGE_DIRS,
]
HEALTH_REPORTING_REGISTRY_ROOT = HEALTH_REPORTING_ROOT / 'registry'
HEALTH_REPORTING_REGISTRY_PACKAGE_DIRS = package_dirs(HEALTH_REPORTING_REGISTRY_ROOT, ('sections',))
HEALTH_REPORTING_PACKAGE_DIRS = [
    HEALTH_REPORTING_ROOT,
    *HEALTH_REPORTING_EXPORT_PACKAGE_DIRS,
    *HEALTH_PRESENTATION_PACKAGE_DIRS,
    *HEALTH_REPORTING_REGISTRY_PACKAGE_DIRS,
]

HEALTH_COMPAT_DIRS = [
    HEALTH_ROOT,
    *HEALTH_AUDIT_PACKAGE_DIRS,
    *HEALTH_CASE_PACKAGE_DIRS,
    *HEALTH_SUITES_PACKAGE_DIRS,
    *HEALTH_REPORTING_PACKAGE_DIRS,
]

__all__ = [
    'HEALTH_AUDIT_CONSISTENCY_PACKAGE_DIRS',
    'HEALTH_AUDIT_CONSISTENCY_ROOT',
    'HEALTH_AUDIT_PACKAGE_DIRS',
    'HEALTH_AUDIT_QUALITY_PACKAGE_DIRS',
    'HEALTH_AUDIT_QUALITY_ROOT',
    'HEALTH_AUDIT_ROUTING_PACKAGE_DIRS',
    'HEALTH_AUDIT_ROUTING_ROOT',
    'HEALTH_AUDITS_ROOT',
    'HEALTH_BASELINE_PACKAGE_DIRS',
    'HEALTH_BASELINES_ROOT',
    'HEALTH_CASE_PACKAGE_DIRS',
    'HEALTH_CASES_ROOT',
    'HEALTH_COMPAT_DIRS',
    'HEALTH_CORE_CHECK_BASELINE_PACKAGE_DIRS',
    'HEALTH_CORE_CHECK_BASELINES_ROOT',
    'HEALTH_CORE_CHECK_HEALTHCHECK_BUILDERS_ROOT',
    'HEALTH_CORE_CHECK_HEALTHCHECK_PACKAGE_DIRS',
    'HEALTH_CORE_CHECK_HEALTHCHECK_ROOT',
    'HEALTH_CORE_CHECK_PACKAGE_DIRS',
    'HEALTH_CORE_CHECKS_ROOT',
    'HEALTH_PRESENTATION_MARKDOWN_PACKAGE_DIRS',
    'HEALTH_PRESENTATION_MARKDOWN_ROOT',
    'HEALTH_PRESENTATION_PACKAGE_DIRS',
    'HEALTH_PRESENTATION_ROOT',
    'HEALTH_PRESENTATION_SUMMARY_PACKAGE_DIRS',
    'HEALTH_PRESENTATION_SUMMARY_ROOT',
    'HEALTH_REPORTING_EXPORT_PACKAGE_DIRS',
    'HEALTH_REPORTING_EXPORTS_ROOT',
    'HEALTH_REPORTING_PACKAGE_DIRS',
    'HEALTH_REPORTING_REGISTRY_PACKAGE_DIRS',
    'HEALTH_REPORTING_REGISTRY_ROOT',
    'HEALTH_REPORTING_ROOT',
    'HEALTH_ROOT',
    'HEALTH_STABILITY_CONSISTENCY_PACKAGE_DIRS',
    'HEALTH_STABILITY_CONSISTENCY_ROOT',
    'HEALTH_STABILITY_PACKAGE_DIRS',
    'HEALTH_STABILITY_PERFORMANCE_PACKAGE_DIRS',
    'HEALTH_STABILITY_PERFORMANCE_ROOT',
    'HEALTH_STABILITY_ROOT',
    'HEALTH_SUITES_PACKAGE_DIRS',
    'HEALTH_SUITES_ROOT',
]
