from __future__ import annotations

from .shared import MODULES_ROOT, nested_package_dirs, package_dirs

LEGACY_ROOT = MODULES_ROOT / 'legacy'

LEGACY_CORE_ROOT = LEGACY_ROOT / 'core'
LEGACY_CORE_ENTRYPOINTS_ROOT = LEGACY_CORE_ROOT / 'entrypoints'
LEGACY_CORE_ENTRYPOINT_PACKAGE_DIRS = package_dirs(
    LEGACY_CORE_ENTRYPOINTS_ROOT,
    ('core', 'bridges'),
)
LEGACY_CORE_BASICS_ROOT = LEGACY_CORE_ROOT / 'basics'
LEGACY_CORE_BASIC_PACKAGE_DIRS = package_dirs(
    LEGACY_CORE_BASICS_ROOT,
    ('runtime', 'math'),
)
LEGACY_CORE_PACKAGE_DIRS = [
    LEGACY_CORE_ROOT,
    *LEGACY_CORE_ENTRYPOINT_PACKAGE_DIRS,
    *LEGACY_CORE_BASIC_PACKAGE_DIRS,
    LEGACY_CORE_ROOT / 'dispatch',
    LEGACY_CORE_ROOT / 'dependencies',
]

LEGACY_RUNTIME_ROOT = LEGACY_ROOT / 'runtime'
LEGACY_RUNTIME_APPLY_ROOT = LEGACY_RUNTIME_ROOT / 'apply'
LEGACY_RUNTIME_SOURCE_LAYERS_ROOT = LEGACY_RUNTIME_APPLY_ROOT / 'source_layers'
LEGACY_RUNTIME_SOURCE_LAYER_PACKAGE_DIRS = package_dirs(
    LEGACY_RUNTIME_SOURCE_LAYERS_ROOT,
    ('build', 'cascade', 'midpatch'),
)
LEGACY_RUNTIME_MODULE_LAYERS_ROOT = LEGACY_RUNTIME_APPLY_ROOT / 'module_layers'
LEGACY_RUNTIME_MODULE_LAYER_PACKAGE_DIRS = package_dirs(
    LEGACY_RUNTIME_MODULE_LAYERS_ROOT,
    ('textbook', 'prompting', 'continuation', 'extended_handlers', 'tail'),
)
LEGACY_RUNTIME_APPLY_PACKAGE_DIRS = [
    LEGACY_RUNTIME_APPLY_ROOT,
    LEGACY_RUNTIME_SOURCE_LAYERS_ROOT,
    *[path for path in LEGACY_RUNTIME_SOURCE_LAYER_PACKAGE_DIRS if path != LEGACY_RUNTIME_SOURCE_LAYERS_ROOT],
    LEGACY_RUNTIME_MODULE_LAYERS_ROOT,
    *[path for path in LEGACY_RUNTIME_MODULE_LAYER_PACKAGE_DIRS if path != LEGACY_RUNTIME_MODULE_LAYERS_ROOT],
    LEGACY_RUNTIME_APPLY_ROOT / 'handler_layers',
]
LEGACY_RUNTIME_LOADERS_ROOT = LEGACY_RUNTIME_ROOT / 'loaders'
LEGACY_RUNTIME_SOURCE_LOADING_ROOT = LEGACY_RUNTIME_LOADERS_ROOT / 'source_loading'
LEGACY_RUNTIME_SOURCE_LOADING_PACKAGE_DIRS = package_dirs(
    LEGACY_RUNTIME_SOURCE_LOADING_ROOT,
    ('blobs', 'exec', 'registry'),
)
LEGACY_RUNTIME_SEEDED_LOADING_ROOT = LEGACY_RUNTIME_LOADERS_ROOT / 'seeded_loading'
LEGACY_RUNTIME_SEEDED_LOADING_PACKAGE_DIRS = package_dirs(
    LEGACY_RUNTIME_SEEDED_LOADING_ROOT,
    ('chain', 'loader'),
)
LEGACY_RUNTIME_NAMESPACE_LOADING_ROOT = LEGACY_RUNTIME_LOADERS_ROOT / 'namespace_loading'
LEGACY_RUNTIME_NAMESPACE_LOADING_PACKAGE_DIRS = package_dirs(
    LEGACY_RUNTIME_NAMESPACE_LOADING_ROOT,
    ('runtime', 'filters'),
)
LEGACY_RUNTIME_BLOB_LOADING_ROOT = LEGACY_RUNTIME_LOADERS_ROOT / 'blob_loading'
LEGACY_RUNTIME_BLOB_LOADING_PACKAGE_DIRS = package_dirs(
    LEGACY_RUNTIME_BLOB_LOADING_ROOT,
    ('runtime',),
)
LEGACY_RUNTIME_LOADER_PACKAGE_DIRS = [
    LEGACY_RUNTIME_LOADERS_ROOT,
    *LEGACY_RUNTIME_SOURCE_LOADING_PACKAGE_DIRS,
    *LEGACY_RUNTIME_SEEDED_LOADING_PACKAGE_DIRS,
    *LEGACY_RUNTIME_NAMESPACE_LOADING_PACKAGE_DIRS,
    *LEGACY_RUNTIME_BLOB_LOADING_PACKAGE_DIRS,
]
LEGACY_RUNTIME_MANIFESTS_ROOT = LEGACY_RUNTIME_ROOT / 'manifests'
LEGACY_RUNTIME_MANIFEST_PACKAGE_DIRS = package_dirs(
    LEGACY_RUNTIME_MANIFESTS_ROOT,
    ('runtime_specs', 'module_shards', 'source_shards'),
)
LEGACY_RUNTIME_INTEGRATIONS_ROOT = LEGACY_RUNTIME_ROOT / 'integrations'
LEGACY_RUNTIME_VENDOR_ROOT = LEGACY_RUNTIME_INTEGRATIONS_ROOT / 'vendors'
LEGACY_RUNTIME_VENDOR_PACKAGE_DIRS = package_dirs(
    LEGACY_RUNTIME_VENDOR_ROOT,
    ('deepseek',),
)
LEGACY_RUNTIME_INTEGRATION_PACKAGE_DIRS = [
    LEGACY_RUNTIME_INTEGRATIONS_ROOT,
    *LEGACY_RUNTIME_VENDOR_PACKAGE_DIRS,
]
LEGACY_RUNTIME_PIPELINE_ROOT = LEGACY_RUNTIME_ROOT / 'pipeline'
LEGACY_RUNTIME_PIPELINE_PACKAGE_DIRS = package_dirs(
    LEGACY_RUNTIME_PIPELINE_ROOT,
    ('base', 'orchestration', 'chain', 'finalize'),
)
LEGACY_RUNTIME_PACKAGE_DIRS = [
    LEGACY_RUNTIME_ROOT,
    *LEGACY_RUNTIME_APPLY_PACKAGE_DIRS,
    *LEGACY_RUNTIME_INTEGRATION_PACKAGE_DIRS,
    *LEGACY_RUNTIME_LOADER_PACKAGE_DIRS,
    *LEGACY_RUNTIME_MANIFEST_PACKAGE_DIRS,
    *LEGACY_RUNTIME_PIPELINE_PACKAGE_DIRS,
]

LEGACY_HANDLERS_ROOT = LEGACY_ROOT / 'handlers'
HANDLER_FAMILY_DIR_NAMES = (
    'change',
    'subject_relations',
    'applied_contexts',
    'arithmetic',
)
LEGACY_PROBLEM_HANDLERS_ROOT = LEGACY_HANDLERS_ROOT / 'problem_handlers'
LEGACY_PROBLEM_HANDLER_DIR_MAP = {
    'change': ('sequential', 'reverse', 'transfer'),
    'subject_relations': ('dual_subject', 'quantity', 'relation'),
    'applied_contexts': ('geometry', 'motion', 'purchase'),
    'arithmetic': ('fractions', 'verbal'),
}
LEGACY_PROBLEM_HANDLER_PACKAGE_DIRS = nested_package_dirs(
    LEGACY_PROBLEM_HANDLERS_ROOT,
    LEGACY_PROBLEM_HANDLER_DIR_MAP,
)
LEGACY_HANDLER_ROUTING_ROOT = LEGACY_HANDLERS_ROOT / 'routing'
LEGACY_HANDLER_ROUTING_PACKAGE_DIRS = package_dirs(
    LEGACY_HANDLER_ROUTING_ROOT,
    ('dispatch', 'enrichment', 'explanatory', 'fallbacks', 'registry'),
)
LEGACY_REVERSE_HANDLER_ROOT = LEGACY_HANDLERS_ROOT / 'reverse_handlers'
LEGACY_REVERSE_HANDLER_PACKAGE_DIRS = package_dirs(
    LEGACY_REVERSE_HANDLER_ROOT,
    ('dual_subject', 'measured', 'transfer'),
)
LEGACY_HANDLER_PACKAGE_DIRS = [
    LEGACY_HANDLERS_ROOT,
    *LEGACY_HANDLER_ROUTING_PACKAGE_DIRS,
    *LEGACY_REVERSE_HANDLER_PACKAGE_DIRS,
    *LEGACY_PROBLEM_HANDLER_PACKAGE_DIRS,
]

LEGACY_SUPPORT_ROOT = LEGACY_ROOT / 'support'
LEGACY_SUPPORT_ANSWERS_ROOT = LEGACY_SUPPORT_ROOT / 'answers'
LEGACY_SUPPORT_FORMATTING_ROOT = LEGACY_SUPPORT_ANSWERS_ROOT / 'formatting'
LEGACY_SUPPORT_FORMATTING_PACKAGE_DIRS = package_dirs(
    LEGACY_SUPPORT_FORMATTING_ROOT,
    ('labels', 'core', 'text'),
)
LEGACY_SUPPORT_VALIDATION_ROOT = LEGACY_SUPPORT_ANSWERS_ROOT / 'validation'
LEGACY_SUPPORT_VALIDATED_ROOT = LEGACY_SUPPORT_VALIDATION_ROOT / 'validated'
LEGACY_SUPPORT_VALIDATED_PACKAGE_DIRS = package_dirs(
    LEGACY_SUPPORT_VALIDATED_ROOT,
    ('ai', 'result'),
)
LEGACY_SUPPORT_VALIDATION_PACKAGE_DIRS = [
    LEGACY_SUPPORT_VALIDATION_ROOT,
    LEGACY_SUPPORT_VALIDATION_ROOT / 'semantics',
    LEGACY_SUPPORT_VALIDATED_ROOT,
    *[path for path in LEGACY_SUPPORT_VALIDATED_PACKAGE_DIRS if path != LEGACY_SUPPORT_VALIDATED_ROOT],
    LEGACY_SUPPORT_VALIDATION_ROOT / 'helpers',
]
LEGACY_SUPPORT_ANSWER_PACKAGE_DIRS = [
    LEGACY_SUPPORT_ANSWERS_ROOT,
    LEGACY_SUPPORT_FORMATTING_ROOT,
    *[path for path in LEGACY_SUPPORT_FORMATTING_PACKAGE_DIRS if path != LEGACY_SUPPORT_FORMATTING_ROOT],
    *LEGACY_SUPPORT_VALIDATION_PACKAGE_DIRS,
    LEGACY_SUPPORT_ANSWERS_ROOT / 'safety',
]
LEGACY_SUPPORT_PARSING_ROOT = LEGACY_SUPPORT_ROOT / 'parsing'
LEGACY_SUPPORT_RELATION_PARSING_PACKAGE_DIRS = package_dirs(
    LEGACY_SUPPORT_PARSING_ROOT / 'relations',
)
LEGACY_SUPPORT_QUANTITY_PARSING_ROOT = LEGACY_SUPPORT_PARSING_ROOT / 'quantities'
LEGACY_SUPPORT_QUANTITY_PARSING_PACKAGE_DIRS = package_dirs(
    LEGACY_SUPPORT_QUANTITY_PARSING_ROOT,
    ('count', 'measure'),
)
LEGACY_SUPPORT_PROBLEM_PARSING_ROOT = LEGACY_SUPPORT_PARSING_ROOT / 'problems'
LEGACY_SUPPORT_PROBLEM_PARSING_PACKAGE_DIRS = package_dirs(
    LEGACY_SUPPORT_PROBLEM_PARSING_ROOT,
    ('core', 'detailed', 'question_flow'),
)
LEGACY_SUPPORT_SCHOOLING_PARSING_PACKAGE_DIRS = package_dirs(
    LEGACY_SUPPORT_PARSING_ROOT / 'schooling',
)
LEGACY_SUPPORT_PARSING_PACKAGE_DIRS = [
    LEGACY_SUPPORT_PARSING_ROOT,
    *LEGACY_SUPPORT_RELATION_PARSING_PACKAGE_DIRS,
    *LEGACY_SUPPORT_QUANTITY_PARSING_PACKAGE_DIRS,
    *LEGACY_SUPPORT_PROBLEM_PARSING_PACKAGE_DIRS,
    *LEGACY_SUPPORT_SCHOOLING_PARSING_PACKAGE_DIRS,
]
LEGACY_SUPPORT_SUBJECT_MODELS_ROOT = LEGACY_SUPPORT_ROOT / 'subject_models'
LEGACY_SUPPORT_ACTION_MODEL_ROOT = LEGACY_SUPPORT_SUBJECT_MODELS_ROOT / 'actions'
LEGACY_SUPPORT_ACTION_MODEL_PACKAGE_DIRS = package_dirs(
    LEGACY_SUPPORT_ACTION_MODEL_ROOT,
    ('dual_subject', 'sequential'),
)
LEGACY_SUPPORT_SUBJECT_MODEL_PACKAGE_DIRS = [
    LEGACY_SUPPORT_SUBJECT_MODELS_ROOT,
    *LEGACY_SUPPORT_ACTION_MODEL_PACKAGE_DIRS,
    LEGACY_SUPPORT_SUBJECT_MODELS_ROOT / 'relations',
    LEGACY_SUPPORT_SUBJECT_MODELS_ROOT / 'transfers',
    LEGACY_SUPPORT_SUBJECT_MODELS_ROOT / 'measured',
]
LEGACY_SUPPORT_PACKAGE_DIRS = [
    LEGACY_SUPPORT_ROOT,
    *LEGACY_SUPPORT_ANSWER_PACKAGE_DIRS,
    *LEGACY_SUPPORT_PARSING_PACKAGE_DIRS,
    LEGACY_SUPPORT_ROOT / 'safety',
    *LEGACY_SUPPORT_SUBJECT_MODEL_PACKAGE_DIRS,
]

__all__ = [
    'HANDLER_FAMILY_DIR_NAMES',
    'LEGACY_CORE_BASIC_PACKAGE_DIRS',
    'LEGACY_CORE_BASICS_ROOT',
    'LEGACY_CORE_ENTRYPOINT_PACKAGE_DIRS',
    'LEGACY_CORE_ENTRYPOINTS_ROOT',
    'LEGACY_CORE_PACKAGE_DIRS',
    'LEGACY_CORE_ROOT',
    'LEGACY_HANDLER_PACKAGE_DIRS',
    'LEGACY_HANDLER_ROUTING_PACKAGE_DIRS',
    'LEGACY_HANDLER_ROUTING_ROOT',
    'LEGACY_HANDLERS_ROOT',
    'LEGACY_PROBLEM_HANDLER_DIR_MAP',
    'LEGACY_PROBLEM_HANDLER_PACKAGE_DIRS',
    'LEGACY_PROBLEM_HANDLERS_ROOT',
    'LEGACY_REVERSE_HANDLER_PACKAGE_DIRS',
    'LEGACY_REVERSE_HANDLER_ROOT',
    'LEGACY_ROOT',
    'LEGACY_RUNTIME_APPLY_PACKAGE_DIRS',
    'LEGACY_RUNTIME_APPLY_ROOT',
    'LEGACY_RUNTIME_BLOB_LOADING_PACKAGE_DIRS',
    'LEGACY_RUNTIME_BLOB_LOADING_ROOT',
    'LEGACY_RUNTIME_INTEGRATION_PACKAGE_DIRS',
    'LEGACY_RUNTIME_INTEGRATIONS_ROOT',
    'LEGACY_RUNTIME_LOADER_PACKAGE_DIRS',
    'LEGACY_RUNTIME_LOADERS_ROOT',
    'LEGACY_RUNTIME_MANIFEST_PACKAGE_DIRS',
    'LEGACY_RUNTIME_MANIFESTS_ROOT',
    'LEGACY_RUNTIME_MODULE_LAYER_PACKAGE_DIRS',
    'LEGACY_RUNTIME_MODULE_LAYERS_ROOT',
    'LEGACY_RUNTIME_NAMESPACE_LOADING_PACKAGE_DIRS',
    'LEGACY_RUNTIME_NAMESPACE_LOADING_ROOT',
    'LEGACY_RUNTIME_PACKAGE_DIRS',
    'LEGACY_RUNTIME_PIPELINE_PACKAGE_DIRS',
    'LEGACY_RUNTIME_PIPELINE_ROOT',
    'LEGACY_RUNTIME_ROOT',
    'LEGACY_RUNTIME_SEEDED_LOADING_PACKAGE_DIRS',
    'LEGACY_RUNTIME_SEEDED_LOADING_ROOT',
    'LEGACY_RUNTIME_SOURCE_LAYER_PACKAGE_DIRS',
    'LEGACY_RUNTIME_SOURCE_LAYERS_ROOT',
    'LEGACY_RUNTIME_SOURCE_LOADING_PACKAGE_DIRS',
    'LEGACY_RUNTIME_SOURCE_LOADING_ROOT',
    'LEGACY_RUNTIME_VENDOR_PACKAGE_DIRS',
    'LEGACY_RUNTIME_VENDOR_ROOT',
    'LEGACY_SUPPORT_ACTION_MODEL_PACKAGE_DIRS',
    'LEGACY_SUPPORT_ACTION_MODEL_ROOT',
    'LEGACY_SUPPORT_ANSWER_PACKAGE_DIRS',
    'LEGACY_SUPPORT_ANSWERS_ROOT',
    'LEGACY_SUPPORT_FORMATTING_PACKAGE_DIRS',
    'LEGACY_SUPPORT_FORMATTING_ROOT',
    'LEGACY_SUPPORT_PACKAGE_DIRS',
    'LEGACY_SUPPORT_PARSING_PACKAGE_DIRS',
    'LEGACY_SUPPORT_PARSING_ROOT',
    'LEGACY_SUPPORT_PROBLEM_PARSING_PACKAGE_DIRS',
    'LEGACY_SUPPORT_PROBLEM_PARSING_ROOT',
    'LEGACY_SUPPORT_QUANTITY_PARSING_PACKAGE_DIRS',
    'LEGACY_SUPPORT_QUANTITY_PARSING_ROOT',
    'LEGACY_SUPPORT_RELATION_PARSING_PACKAGE_DIRS',
    'LEGACY_SUPPORT_ROOT',
    'LEGACY_SUPPORT_SCHOOLING_PARSING_PACKAGE_DIRS',
    'LEGACY_SUPPORT_SUBJECT_MODEL_PACKAGE_DIRS',
    'LEGACY_SUPPORT_SUBJECT_MODELS_ROOT',
    'LEGACY_SUPPORT_VALIDATED_PACKAGE_DIRS',
    'LEGACY_SUPPORT_VALIDATED_ROOT',
    'LEGACY_SUPPORT_VALIDATION_PACKAGE_DIRS',
    'LEGACY_SUPPORT_VALIDATION_ROOT',
]
