from __future__ import annotations

from .shared import RUNTIME_ASSETS_ROOT, nested_package_dirs, package_dirs

RUNTIME_ASSETS_PREPARED_ROOT = RUNTIME_ASSETS_ROOT / 'prepared'
RUNTIME_ASSETS_LEGACY_WRAPPERS_ROOT = RUNTIME_ASSETS_ROOT / 'legacy_wrappers'
RUNTIME_ASSETS_FALLBACKS_ROOT = RUNTIME_ASSETS_ROOT / 'fallbacks'
RUNTIME_ASSETS_FALLBACK_RUNTIME_SOURCES_ROOT = RUNTIME_ASSETS_FALLBACKS_ROOT / 'runtime_sources'
RUNTIME_ASSETS_FALLBACK_RUNTIME_MODULES_ROOT = RUNTIME_ASSETS_FALLBACKS_ROOT / 'runtime_modules'
RUNTIME_ASSETS_FALLBACK_HANDLER_SOURCES_ROOT = RUNTIME_ASSETS_FALLBACKS_ROOT / 'handler_sources'
RUNTIME_ASSETS_SHARD_RESERVE_ROOT = RUNTIME_ASSETS_ROOT / 'shard_reserve'
RUNTIME_ASSETS_SHARED_BODIES_ROOT = RUNTIME_ASSETS_ROOT / 'shared_bodies'

RUNTIME_ASSET_GROUP_ROOTS = [
    RUNTIME_ASSETS_PREPARED_ROOT,
    RUNTIME_ASSETS_LEGACY_WRAPPERS_ROOT,
    RUNTIME_ASSETS_FALLBACKS_ROOT,
    RUNTIME_ASSETS_FALLBACK_RUNTIME_SOURCES_ROOT,
    RUNTIME_ASSETS_FALLBACK_RUNTIME_MODULES_ROOT,
    RUNTIME_ASSETS_FALLBACK_HANDLER_SOURCES_ROOT,
    RUNTIME_ASSETS_SHARD_RESERVE_ROOT,
]

STATIC_RUNTIME_SOURCES_ROOT = RUNTIME_ASSETS_PREPARED_ROOT / 'static_runtime_sources'
STATIC_RUNTIME_SOURCE_PACKAGE_DIRS = package_dirs(
    STATIC_RUNTIME_SOURCES_ROOT,
    ('build', 'cascade', 'midpatch'),
)
STATIC_RUNTIME_MODULES_ROOT = RUNTIME_ASSETS_PREPARED_ROOT / 'static_runtime_modules'
STATIC_RUNTIME_MODULE_PACKAGE_DIRS = package_dirs(
    STATIC_RUNTIME_MODULES_ROOT,
    ('textbook', 'prompting', 'continuation', 'handlers', 'tail'),
)
STATIC_HANDLER_SOURCES_ROOT = RUNTIME_ASSETS_PREPARED_ROOT / 'static_handler_sources'
HANDLER_SOURCE_LEAF_DIR_MAP = {
    'change': ('sequential',),
    'subject_relations': ('dual_subject', 'quantity', 'relation'),
    'applied_contexts': ('geometry', 'motion', 'purchase'),
    'arithmetic': ('fractions', 'verbal'),
}
STATIC_HANDLER_SOURCE_PACKAGE_DIRS = nested_package_dirs(
    STATIC_HANDLER_SOURCES_ROOT,
    HANDLER_SOURCE_LEAF_DIR_MAP,
)


SHARED_RUNTIME_SOURCE_BODIES_ROOT = RUNTIME_ASSETS_SHARED_BODIES_ROOT / 'runtime_sources'
SHARED_RUNTIME_SOURCE_BODY_PACKAGE_DIRS = package_dirs(
    SHARED_RUNTIME_SOURCE_BODIES_ROOT,
    ('build', 'cascade', 'midpatch'),
)
SHARED_RUNTIME_MODULE_BODIES_ROOT = RUNTIME_ASSETS_SHARED_BODIES_ROOT / 'runtime_modules'
SHARED_RUNTIME_MODULE_BODY_PACKAGE_DIRS = package_dirs(
    SHARED_RUNTIME_MODULE_BODIES_ROOT,
    ('textbook', 'prompting', 'continuation', 'handlers', 'tail'),
)
SHARED_HANDLER_SOURCE_BODIES_ROOT = RUNTIME_ASSETS_SHARED_BODIES_ROOT / 'handler_sources'
SHARED_HANDLER_SOURCE_BODY_PACKAGE_DIRS = nested_package_dirs(
    SHARED_HANDLER_SOURCE_BODIES_ROOT,
    HANDLER_SOURCE_LEAF_DIR_MAP,
)

STATIC_RUNTIME_SOURCE_IMPORT_PACKAGE_DIRS = SHARED_RUNTIME_SOURCE_BODY_PACKAGE_DIRS
STATIC_RUNTIME_MODULE_IMPORT_PACKAGE_DIRS = SHARED_RUNTIME_MODULE_BODY_PACKAGE_DIRS
STATIC_HANDLER_SOURCE_IMPORT_PACKAGE_DIRS = SHARED_HANDLER_SOURCE_BODY_PACKAGE_DIRS
SEEDED_RUNTIME_SOURCE_FALLBACK_IMPORT_PACKAGE_DIRS = SHARED_RUNTIME_SOURCE_BODY_PACKAGE_DIRS
SEEDED_RUNTIME_MODULE_FALLBACK_IMPORT_PACKAGE_DIRS = SHARED_RUNTIME_MODULE_BODY_PACKAGE_DIRS
MATERIALIZED_HANDLER_SOURCE_FALLBACK_IMPORT_PACKAGE_DIRS = SHARED_HANDLER_SOURCE_BODY_PACKAGE_DIRS

LEGACY_RUNTIME_SOURCES_ROOT = RUNTIME_ASSETS_LEGACY_WRAPPERS_ROOT / 'legacy_runtime_sources'
LEGACY_RUNTIME_SOURCE_WRAPPER_PACKAGE_DIRS = package_dirs(
    LEGACY_RUNTIME_SOURCES_ROOT,
    ('build', 'cascade', 'midpatch'),
)
LEGACY_RUNTIME_MODULES_ROOT = RUNTIME_ASSETS_LEGACY_WRAPPERS_ROOT / 'legacy_runtime_modules'
LEGACY_RUNTIME_MODULE_WRAPPER_PACKAGE_DIRS = package_dirs(
    LEGACY_RUNTIME_MODULES_ROOT,
    ('textbook', 'prompting', 'continuation', 'handlers', 'tail'),
)
LEGACY_HANDLER_SOURCES_ROOT = RUNTIME_ASSETS_LEGACY_WRAPPERS_ROOT / 'legacy_handler_sources'
LEGACY_HANDLER_SOURCE_PACKAGE_DIRS = nested_package_dirs(
    LEGACY_HANDLER_SOURCES_ROOT,
    HANDLER_SOURCE_LEAF_DIR_MAP,
)

SEEDED_RUNTIME_SOURCE_FALLBACKS_ROOT = RUNTIME_ASSETS_FALLBACK_RUNTIME_SOURCES_ROOT / 'seeded_runtime_source_fallbacks'
SEEDED_RUNTIME_SOURCE_FALLBACK_PACKAGE_DIRS = package_dirs(
    SEEDED_RUNTIME_SOURCE_FALLBACKS_ROOT,
    ('build', 'cascade', 'midpatch'),
)
SEEDED_RUNTIME_MODULE_FALLBACKS_ROOT = RUNTIME_ASSETS_FALLBACK_RUNTIME_MODULES_ROOT / 'seeded_runtime_module_fallbacks'
SEEDED_RUNTIME_MODULE_FALLBACK_PACKAGE_DIRS = package_dirs(
    SEEDED_RUNTIME_MODULE_FALLBACKS_ROOT,
    ('textbook', 'prompting', 'continuation', 'handlers', 'tail'),
)
MATERIALIZED_HANDLER_SOURCE_FALLBACKS_ROOT = RUNTIME_ASSETS_FALLBACK_HANDLER_SOURCES_ROOT / 'materialized_handler_source_fallbacks'
MATERIALIZED_HANDLER_SOURCE_FALLBACK_PACKAGE_DIRS = nested_package_dirs(
    MATERIALIZED_HANDLER_SOURCE_FALLBACKS_ROOT,
    HANDLER_SOURCE_LEAF_DIR_MAP,
)
SEEDED_HANDLER_SOURCE_FALLBACKS_ROOT = RUNTIME_ASSETS_FALLBACK_HANDLER_SOURCES_ROOT / 'seeded_handler_source_fallbacks'
SEEDED_HANDLER_SOURCE_FALLBACK_PACKAGE_DIRS = nested_package_dirs(
    SEEDED_HANDLER_SOURCE_FALLBACKS_ROOT,
    HANDLER_SOURCE_LEAF_DIR_MAP,
)

LEGACY_RUNTIME_SHARDS_ROOT = RUNTIME_ASSETS_SHARD_RESERVE_ROOT / 'legacy_runtime_shards'
LEGACY_RUNTIME_MODULE_SHARDS_ROOT = RUNTIME_ASSETS_SHARD_RESERVE_ROOT / 'legacy_runtime_module_shards'
PREPATCH_BUILD_SOURCE_ROOT = LEGACY_RUNTIME_SHARDS_ROOT / 'prepatch_build_source'
PREPATCH_BUILD_SOURCE_PACKAGE_DIRS = package_dirs(
    PREPATCH_BUILD_SOURCE_ROOT,
    ('batch_01_05', 'batch_06_10', 'batch_11_15', 'batch_16_20', 'batch_21_25'),
)
PREPATCH_CASCADE_SOURCE_ROOT = LEGACY_RUNTIME_SHARDS_ROOT / 'prepatch_cascade_source'
PREPATCH_CASCADE_SOURCE_PACKAGE_DIRS = package_dirs(
    PREPATCH_CASCADE_SOURCE_ROOT,
    ('batch_01_05', 'batch_06_10', 'batch_11_14'),
)
MIDPATCH_RUNTIME_SOURCE_ROOT = LEGACY_RUNTIME_SHARDS_ROOT / 'midpatch_runtime_source'
MIDPATCH_RUNTIME_SOURCE_PACKAGE_DIRS = package_dirs(
    MIDPATCH_RUNTIME_SOURCE_ROOT,
    ('batch_01_05', 'batch_06_10', 'batch_11_15'),
)
LEGACY_RUNTIME_SHARD_PACKAGE_DIRS = [
    LEGACY_RUNTIME_SHARDS_ROOT,
    *PREPATCH_BUILD_SOURCE_PACKAGE_DIRS,
    *PREPATCH_CASCADE_SOURCE_PACKAGE_DIRS,
    *MIDPATCH_RUNTIME_SOURCE_PACKAGE_DIRS,
]

RUNTIME_ASSET_PACKAGE_DIRS = {
    'static_runtime_sources': STATIC_RUNTIME_SOURCES_ROOT,
    'static_runtime_modules': STATIC_RUNTIME_MODULES_ROOT,
    'static_handler_sources': STATIC_HANDLER_SOURCES_ROOT,
    'legacy_runtime_sources': LEGACY_RUNTIME_SOURCES_ROOT,
    'legacy_runtime_modules': LEGACY_RUNTIME_MODULES_ROOT,
    'legacy_handler_sources': LEGACY_HANDLER_SOURCES_ROOT,
    'seeded_runtime_source_fallbacks': SEEDED_RUNTIME_SOURCE_FALLBACKS_ROOT,
    'seeded_runtime_module_fallbacks': SEEDED_RUNTIME_MODULE_FALLBACKS_ROOT,
    'materialized_handler_source_fallbacks': MATERIALIZED_HANDLER_SOURCE_FALLBACKS_ROOT,
    'seeded_handler_source_fallbacks': SEEDED_HANDLER_SOURCE_FALLBACKS_ROOT,
    'legacy_runtime_shards': LEGACY_RUNTIME_SHARDS_ROOT,
    'legacy_runtime_module_shards': LEGACY_RUNTIME_MODULE_SHARDS_ROOT,
}

__all__ = [
    'HANDLER_SOURCE_LEAF_DIR_MAP',
    'LEGACY_HANDLER_SOURCE_PACKAGE_DIRS',
    'LEGACY_HANDLER_SOURCES_ROOT',
    'LEGACY_RUNTIME_MODULE_SHARDS_ROOT',
    'LEGACY_RUNTIME_MODULE_WRAPPER_PACKAGE_DIRS',
    'LEGACY_RUNTIME_MODULES_ROOT',
    'LEGACY_RUNTIME_SHARD_PACKAGE_DIRS',
    'LEGACY_RUNTIME_SHARDS_ROOT',
    'LEGACY_RUNTIME_SOURCE_WRAPPER_PACKAGE_DIRS',
    'LEGACY_RUNTIME_SOURCES_ROOT',
    'MATERIALIZED_HANDLER_SOURCE_FALLBACK_PACKAGE_DIRS',
    'MATERIALIZED_HANDLER_SOURCE_FALLBACKS_ROOT',
    'MIDPATCH_RUNTIME_SOURCE_PACKAGE_DIRS',
    'MIDPATCH_RUNTIME_SOURCE_ROOT',
    'PREPATCH_BUILD_SOURCE_PACKAGE_DIRS',
    'PREPATCH_BUILD_SOURCE_ROOT',
    'PREPATCH_CASCADE_SOURCE_PACKAGE_DIRS',
    'PREPATCH_CASCADE_SOURCE_ROOT',
    'RUNTIME_ASSET_GROUP_ROOTS',
    'RUNTIME_ASSETS_SHARED_BODIES_ROOT',
    'SHARED_HANDLER_SOURCE_BODIES_ROOT',
    'SHARED_HANDLER_SOURCE_BODY_PACKAGE_DIRS',
    'MATERIALIZED_HANDLER_SOURCE_FALLBACK_IMPORT_PACKAGE_DIRS',
    'SEEDED_RUNTIME_MODULE_FALLBACK_IMPORT_PACKAGE_DIRS',
    'SEEDED_RUNTIME_SOURCE_FALLBACK_IMPORT_PACKAGE_DIRS',
    'SHARED_RUNTIME_MODULE_BODIES_ROOT',
    'SHARED_RUNTIME_MODULE_BODY_PACKAGE_DIRS',
    'SHARED_RUNTIME_SOURCE_BODIES_ROOT',
    'SHARED_RUNTIME_SOURCE_BODY_PACKAGE_DIRS',
    'RUNTIME_ASSET_PACKAGE_DIRS',
    'RUNTIME_ASSETS_FALLBACK_HANDLER_SOURCES_ROOT',
    'RUNTIME_ASSETS_FALLBACK_RUNTIME_MODULES_ROOT',
    'RUNTIME_ASSETS_FALLBACK_RUNTIME_SOURCES_ROOT',
    'RUNTIME_ASSETS_FALLBACKS_ROOT',
    'RUNTIME_ASSETS_LEGACY_WRAPPERS_ROOT',
    'RUNTIME_ASSETS_PREPARED_ROOT',
    'RUNTIME_ASSETS_ROOT',
    'RUNTIME_ASSETS_SHARD_RESERVE_ROOT',
    'SEEDED_HANDLER_SOURCE_FALLBACK_PACKAGE_DIRS',
    'SEEDED_HANDLER_SOURCE_FALLBACKS_ROOT',
    'SEEDED_RUNTIME_MODULE_FALLBACK_PACKAGE_DIRS',
    'SEEDED_RUNTIME_MODULE_FALLBACKS_ROOT',
    'SEEDED_RUNTIME_SOURCE_FALLBACK_PACKAGE_DIRS',
    'SEEDED_RUNTIME_SOURCE_FALLBACKS_ROOT',
    'STATIC_HANDLER_SOURCE_IMPORT_PACKAGE_DIRS',
    'STATIC_HANDLER_SOURCE_PACKAGE_DIRS',
    'STATIC_HANDLER_SOURCES_ROOT',
    'STATIC_RUNTIME_MODULE_IMPORT_PACKAGE_DIRS',
    'STATIC_RUNTIME_MODULE_PACKAGE_DIRS',
    'STATIC_RUNTIME_MODULES_ROOT',
    'STATIC_RUNTIME_SOURCE_IMPORT_PACKAGE_DIRS',
    'STATIC_RUNTIME_SOURCE_PACKAGE_DIRS',
    'STATIC_RUNTIME_SOURCES_ROOT',
]
