from __future__ import annotations

from .shared import MODULES_ROOT, package_dirs

RUNTIME_ROOT = MODULES_ROOT / 'runtime'

RUNTIME_REGISTRY_ROOT = RUNTIME_ROOT / 'registry'
RUNTIME_REGISTRY_CHAIN_ROOT = RUNTIME_REGISTRY_ROOT / 'chains'
RUNTIME_REGISTRY_CHAIN_PACKAGE_DIRS = package_dirs(
    RUNTIME_REGISTRY_CHAIN_ROOT,
    ('exports', 'specs', 'static'),
)
RUNTIME_REGISTRY_HANDLER_ROOT = RUNTIME_REGISTRY_ROOT / 'registry_handlers'
RUNTIME_REGISTRY_HANDLER_PROXY_ROOT = RUNTIME_REGISTRY_HANDLER_ROOT / 'proxies'
RUNTIME_REGISTRY_HANDLER_PROXY_PACKAGE_DIRS = package_dirs(
    RUNTIME_REGISTRY_HANDLER_PROXY_ROOT,
    ('factory',),
)
RUNTIME_REGISTRY_HANDLER_SOURCE_ROOT = RUNTIME_REGISTRY_HANDLER_ROOT / 'sources'
RUNTIME_REGISTRY_HANDLER_SOURCE_PACKAGE_DIRS = package_dirs(
    RUNTIME_REGISTRY_HANDLER_SOURCE_ROOT,
    ('registry',),
)
RUNTIME_REGISTRY_HANDLER_PACKAGE_DIRS = [
    RUNTIME_REGISTRY_HANDLER_ROOT,
    *RUNTIME_REGISTRY_HANDLER_PROXY_PACKAGE_DIRS,
    *RUNTIME_REGISTRY_HANDLER_SOURCE_PACKAGE_DIRS,
]
RUNTIME_REGISTRY_RESOLUTION_ROOT = RUNTIME_REGISTRY_ROOT / 'resolution'
RUNTIME_REGISTRY_RESOLUTION_PACKAGE_DIRS = package_dirs(
    RUNTIME_REGISTRY_RESOLUTION_ROOT,
    ('runtime_assets',),
)
RUNTIME_REGISTRY_PACKAGE_DIRS = [
    RUNTIME_REGISTRY_ROOT,
    *RUNTIME_REGISTRY_CHAIN_PACKAGE_DIRS,
    *RUNTIME_REGISTRY_HANDLER_PACKAGE_DIRS,
    *RUNTIME_REGISTRY_RESOLUTION_PACKAGE_DIRS,
]

RUNTIME_NAMESPACE_ROOT = RUNTIME_ROOT / 'namespace'
RUNTIME_NAMESPACE_FACTORY_ROOT = RUNTIME_NAMESPACE_ROOT / 'factories'
RUNTIME_NAMESPACE_FACTORY_PACKAGE_DIRS = package_dirs(
    RUNTIME_NAMESPACE_FACTORY_ROOT,
    ('adoption', 'builder'),
)
RUNTIME_NAMESPACE_PACKAGE_DIRS = [
    RUNTIME_NAMESPACE_ROOT,
    RUNTIME_NAMESPACE_ROOT / 'bootstrap',
    RUNTIME_NAMESPACE_ROOT / 'cache',
    *RUNTIME_NAMESPACE_FACTORY_PACKAGE_DIRS,
]

RUNTIME_AUDIT_ROOT = RUNTIME_ROOT / 'audit'
RUNTIME_AUDIT_CONTRACTS_ROOT = RUNTIME_AUDIT_ROOT / 'contracts'
RUNTIME_AUDIT_CONTRACT_SUITES_ROOT = RUNTIME_AUDIT_CONTRACTS_ROOT / 'suites'
RUNTIME_AUDIT_CONTRACT_SUITE_PACKAGE_DIRS = package_dirs(
    RUNTIME_AUDIT_CONTRACT_SUITES_ROOT,
    ('builders',),
)
RUNTIME_AUDIT_CONTRACT_PACKAGE_DIRS = [
    RUNTIME_AUDIT_CONTRACTS_ROOT,
    *RUNTIME_AUDIT_CONTRACT_SUITE_PACKAGE_DIRS,
]
RUNTIME_AUDIT_MANIFESTS_ROOT = RUNTIME_AUDIT_ROOT / 'manifests'
RUNTIME_AUDIT_MANIFEST_PACKAGE_DIRS = package_dirs(
    RUNTIME_AUDIT_MANIFESTS_ROOT,
    ('runtime',),
)
RUNTIME_AUDIT_REGRESSIONS_ROOT = RUNTIME_AUDIT_ROOT / 'regressions'
RUNTIME_AUDIT_REGRESSION_MODULE_ROOT = RUNTIME_AUDIT_REGRESSIONS_ROOT / 'modules'
RUNTIME_AUDIT_REGRESSION_PACKAGE_DIRS = [
    RUNTIME_AUDIT_REGRESSIONS_ROOT,
    RUNTIME_AUDIT_REGRESSION_MODULE_ROOT,
    RUNTIME_AUDIT_REGRESSION_MODULE_ROOT / 'runtime',
]
RUNTIME_AUDIT_NAMESPACE_CHECKS_ROOT = RUNTIME_AUDIT_ROOT / 'namespace_checks'
RUNTIME_AUDIT_NAMESPACE_CHECK_PACKAGE_DIRS = package_dirs(
    RUNTIME_AUDIT_NAMESPACE_CHECKS_ROOT,
    ('audits',),
)
RUNTIME_AUDIT_SOURCE_CHECKS_ROOT = RUNTIME_AUDIT_ROOT / 'source_checks'
RUNTIME_AUDIT_SOURCE_CHECK_PACKAGE_DIRS = package_dirs(
    RUNTIME_AUDIT_SOURCE_CHECKS_ROOT,
    ('analysis',),
)
RUNTIME_AUDIT_PACKAGE_DIRS = [
    RUNTIME_AUDIT_ROOT,
    *RUNTIME_AUDIT_CONTRACT_PACKAGE_DIRS,
    *RUNTIME_AUDIT_MANIFEST_PACKAGE_DIRS,
    *RUNTIME_AUDIT_REGRESSION_PACKAGE_DIRS,
    *RUNTIME_AUDIT_NAMESPACE_CHECK_PACKAGE_DIRS,
    *RUNTIME_AUDIT_SOURCE_CHECK_PACKAGE_DIRS,
]

RUNTIME_REPORTING_ROOT = RUNTIME_ROOT / 'reporting'
RUNTIME_REPORTING_DIAGNOSTICS_ROOT = RUNTIME_REPORTING_ROOT / 'diagnostics'
RUNTIME_REPORTING_DIAGNOSTIC_REPORT_ROOT = RUNTIME_REPORTING_DIAGNOSTICS_ROOT / 'reports'
RUNTIME_REPORTING_DIAGNOSTIC_REPORT_PACKAGE_DIRS = package_dirs(
    RUNTIME_REPORTING_DIAGNOSTIC_REPORT_ROOT,
    ('builders',),
)
RUNTIME_REPORTING_DIAGNOSTIC_FINGERPRINT_ROOT = RUNTIME_REPORTING_DIAGNOSTICS_ROOT / 'fingerprints'
RUNTIME_REPORTING_DIAGNOSTIC_FINGERPRINT_PACKAGE_DIRS = package_dirs(
    RUNTIME_REPORTING_DIAGNOSTIC_FINGERPRINT_ROOT,
    ('builders',),
)
RUNTIME_REPORTING_DIAGNOSTIC_PACKAGE_DIRS = [
    RUNTIME_REPORTING_DIAGNOSTICS_ROOT,
    *RUNTIME_REPORTING_DIAGNOSTIC_REPORT_PACKAGE_DIRS,
    *RUNTIME_REPORTING_DIAGNOSTIC_FINGERPRINT_PACKAGE_DIRS,
]
RUNTIME_REPORTING_INVENTORY_ROOT = RUNTIME_REPORTING_ROOT / 'inventory'
RUNTIME_REPORTING_INVENTORY_PACKAGE_DIRS = package_dirs(
    RUNTIME_REPORTING_INVENTORY_ROOT,
    ('symbols',),
)
RUNTIME_REPORTING_PACKAGE_DIRS = [
    RUNTIME_REPORTING_ROOT,
    *RUNTIME_REPORTING_DIAGNOSTIC_PACKAGE_DIRS,
    *RUNTIME_REPORTING_INVENTORY_PACKAGE_DIRS,
]

RUNTIME_COMPAT_DIRS = [
    RUNTIME_ROOT,
    *RUNTIME_NAMESPACE_PACKAGE_DIRS,
    *RUNTIME_AUDIT_PACKAGE_DIRS,
    *RUNTIME_REGISTRY_PACKAGE_DIRS,
    *RUNTIME_REPORTING_PACKAGE_DIRS,
]

__all__ = [
    'RUNTIME_AUDIT_CONTRACT_PACKAGE_DIRS',
    'RUNTIME_AUDIT_CONTRACTS_ROOT',
    'RUNTIME_AUDIT_CONTRACT_SUITE_PACKAGE_DIRS',
    'RUNTIME_AUDIT_CONTRACT_SUITES_ROOT',
    'RUNTIME_AUDIT_MANIFEST_PACKAGE_DIRS',
    'RUNTIME_AUDIT_MANIFESTS_ROOT',
    'RUNTIME_AUDIT_NAMESPACE_CHECK_PACKAGE_DIRS',
    'RUNTIME_AUDIT_NAMESPACE_CHECKS_ROOT',
    'RUNTIME_AUDIT_PACKAGE_DIRS',
    'RUNTIME_AUDIT_REGRESSION_MODULE_ROOT',
    'RUNTIME_AUDIT_REGRESSION_PACKAGE_DIRS',
    'RUNTIME_AUDIT_REGRESSIONS_ROOT',
    'RUNTIME_AUDIT_ROOT',
    'RUNTIME_AUDIT_SOURCE_CHECK_PACKAGE_DIRS',
    'RUNTIME_AUDIT_SOURCE_CHECKS_ROOT',
    'RUNTIME_COMPAT_DIRS',
    'RUNTIME_NAMESPACE_FACTORY_PACKAGE_DIRS',
    'RUNTIME_NAMESPACE_FACTORY_ROOT',
    'RUNTIME_NAMESPACE_PACKAGE_DIRS',
    'RUNTIME_NAMESPACE_ROOT',
    'RUNTIME_REGISTRY_CHAIN_PACKAGE_DIRS',
    'RUNTIME_REGISTRY_CHAIN_ROOT',
    'RUNTIME_REGISTRY_HANDLER_PACKAGE_DIRS',
    'RUNTIME_REGISTRY_HANDLER_PROXY_PACKAGE_DIRS',
    'RUNTIME_REGISTRY_HANDLER_PROXY_ROOT',
    'RUNTIME_REGISTRY_HANDLER_ROOT',
    'RUNTIME_REGISTRY_HANDLER_SOURCE_PACKAGE_DIRS',
    'RUNTIME_REGISTRY_HANDLER_SOURCE_ROOT',
    'RUNTIME_REGISTRY_PACKAGE_DIRS',
    'RUNTIME_REGISTRY_RESOLUTION_PACKAGE_DIRS',
    'RUNTIME_REGISTRY_RESOLUTION_ROOT',
    'RUNTIME_REGISTRY_ROOT',
    'RUNTIME_REPORTING_DIAGNOSTIC_FINGERPRINT_PACKAGE_DIRS',
    'RUNTIME_REPORTING_DIAGNOSTIC_FINGERPRINT_ROOT',
    'RUNTIME_REPORTING_DIAGNOSTIC_PACKAGE_DIRS',
    'RUNTIME_REPORTING_DIAGNOSTIC_REPORT_PACKAGE_DIRS',
    'RUNTIME_REPORTING_DIAGNOSTIC_REPORT_ROOT',
    'RUNTIME_REPORTING_DIAGNOSTICS_ROOT',
    'RUNTIME_REPORTING_INVENTORY_PACKAGE_DIRS',
    'RUNTIME_REPORTING_INVENTORY_ROOT',
    'RUNTIME_REPORTING_PACKAGE_DIRS',
    'RUNTIME_REPORTING_ROOT',
    'RUNTIME_ROOT',
]
