from __future__ import annotations

from backend.package_bootstrap import bootstrap_package

from backend.compat_paths import (
    RUNTIME_ASSETS_FALLBACKS_ROOT,
    RUNTIME_ASSETS_FALLBACK_HANDLER_SOURCES_ROOT,
    RUNTIME_ASSETS_FALLBACK_RUNTIME_MODULES_ROOT,
    RUNTIME_ASSETS_FALLBACK_RUNTIME_SOURCES_ROOT,
    extend_module_path,
)

__path__ = bootstrap_package(
    __path__,
    __name__,
    [
            RUNTIME_ASSETS_FALLBACKS_ROOT,
            RUNTIME_ASSETS_FALLBACK_RUNTIME_SOURCES_ROOT,
            RUNTIME_ASSETS_FALLBACK_RUNTIME_MODULES_ROOT,
            RUNTIME_ASSETS_FALLBACK_HANDLER_SOURCES_ROOT,
        ],
)

__all__ = [
    'RUNTIME_ASSETS_FALLBACKS_ROOT',
    'RUNTIME_ASSETS_FALLBACK_RUNTIME_SOURCES_ROOT',
    'RUNTIME_ASSETS_FALLBACK_RUNTIME_MODULES_ROOT',
    'RUNTIME_ASSETS_FALLBACK_HANDLER_SOURCES_ROOT',
]
